# Generated by Django 6.0.1 on 2026-02-18 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VetVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_time', models.DateTimeField()),
                ('reason', models.CharField(max_length=200)),
                ('weight_lbs', models.DecimalField(decimal_places=1, max_digits=4)),
                ('paid', models.BooleanField(default=False)),
                ('cost_usd', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cats.cat')),
            ],
        ),
    ]
